### ISSUE TITLE
Testing exception (promise rejection)

### ISSUE THREAD

**Issue by MichalLytek** [wallabyjs/wallaby-chai-as-promised#1]
I have a problem with testing promise rejection. This test correctly don't pass because the promise was rejected:

``` typescript
it("should test promise throwing error", () => {
    const promiseThrowingError = () => {
        return new Promise((resolve, reject) => {
            return reject(new Error("Error from promise"));
        });
    };
    return expect(promiseThrowingError()).to.not.be.rejected;
});
```

And in console I got info:

```
 ​​​​ should test promise throwing error​​​​ ​​​[0 ms]​​​​
    ​​​​
    ​​expected promise not to be rejected but it was rejected with 'Error: Error from promise'​​
```

But the problem is that wallaby don't mark it like synchronous `expect` on synchronous throwing error - no red square on left, no red error info on bad line, just pink squares on left on the whole `it` test.

![Imgur](http://i.imgur.com/XXWNZHs.png)

But if I do this simple code:

``` typescript
it("should test promise throwing error", () => {
    const rejectedPromise = Promise.reject(new Error("Error from promise"));
    return rejectedPromise;
});
```

It works ok, I got a red info on line with `new Error` and red square on this line.
But if I remove `new Error` and reject promise with a string:

``` typescript
it("should test promise throwing error", () => {
    const rejectedPromise = Promise.reject("Error from promise");
    return rejectedPromise;
});
```

It stops working again. So it looks like `chai-as-promised` don't reject promise with `new Error` when the assertion fails (`return expect(promiseThrowingError()).to.not.be.rejected;`) but with custom object.

It would be nice if you recognize this object and provide info in IDE when `chai-as-promised` assertion failed - inline red info `​​expected promise not to be rejected but it was rejected with 'Error: Error from promise'​​`. It would be very helpful in test with async/await with multiple assertion - I could locate the place which `expect` failed.

**Comment by ArtemGovorov** [comment]
@19majkel94 I'm investigating what can be done. Could you please share your wallaby.js config?

**Comment by MichalLytek** [comment]
Sure! 😉 

``` javascript
module.exports = function (w) {

    return {
        files: [
            "src/**/*.ts",
            "files/**",
            "views/**",
            "!src/tests/**"
        ],

        tests: [
            "src/tests/**/*.ts"
        ],

        env: {
            type: 'node'
        },

        compilers: {
            '**/*.ts': w.compilers.typeScript({ module: 'commonjs' })
        }
    };
};
```

**Comment by ArtemGovorov** [comment]
So I have done some investigating and added the better support for `chai-as-promised`-like scenarios to [wallaby core 1.0.303](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

Now the test like below will correctly mark the error lines:

``` javascript
it("should test promise throwing error", () => {
    const promiseThrowingError = () => {
        return new Promise((resolve, reject) => {
            return reject(new Error("Error from promise"));
        });
    };
    return expect(promiseThrowingError()).to.not.be.rejected;
});
```

<img width="717" alt="screen shot 2016-10-10 at 12 28 14 pm" src="https://cloud.githubusercontent.com/assets/979966/19225772/0d0d2e6a-8ee5-11e6-9773-85d5972e80e5.png">

However the scenario when not Error type is used for a promise rejection is different, and will still not work:

``` javascript
it("should test promise throwing error", () => {
    const rejectedPromise = Promise.reject("Error from promise");
    return rejectedPromise;
});
```

This happens for a couple of reasons: because `mocha` requires the error (as indicated in its error message) and because there's no stack that can be captured from a string in order to map the error to certain code line.

<img width="583" alt="screen shot 2016-10-10 at 12 24 17 pm" src="https://cloud.githubusercontent.com/assets/979966/19225735/90906e06-8ee4-11e6-89a0-0ecf14c13647.png">

**Comment by MichalLytek** [comment]
I've updated wallaby core to 1.0.303 but still this example doesn't work like on your screenshot.

![Imgur](http://i.imgur.com/dIGZusu.png)

I will wait, maybe next update of VS Code extension will get this added feature :wink:

**Comment by ArtemGovorov** [comment]
@19majkel94 I was testing against this repo (with `chai-as-promised@5.3`) and when I tried with `chai-as-promised@6` I got the same issue, so you're probably using v6. Upon investigating, there [was the breaking change in the `chai-as-promised@6`](https://github.com/domenic/chai-as-promised/issues/166#issuecomment-252792883), so that now the library doesn't report the error stack anymore, but the error message string. So the only workaround for now is to use `chai-as-promised@5.3`.

**Comment by MichalLytek** [comment]
Ok, now it works :)
But still there's left one use case:

``` typescript
return expect(promiseThrowingError()).to.be.rejectedWith(Error, "Not Error from promise");
```

![Imgur](http://i.imgur.com/YHDFUfF.png)

But i see that there is no stack trace so you can't to antything until it's fixed in new `chai-as-promised`?

This example works:

``` typescript
 return expect(promiseThrowingError()).to.be.rejectedWith(BadRequestError, "Error from promise");
```

```
​​expected promise to be rejected with 'BadRequestError' but it was rejected with [Error: Error from promise]​​
      at ​src/tests/unit/controllers/category.ts:270:12​
      at ​src/tests/unit/controllers/category.ts:269:8​
      at ​src/tests/unit/controllers/category.ts:273:4​
```

**Comment by ArtemGovorov** [comment]
@19majkel94 Cool, thanks for checking. 

> But i see that there is no stack trace so you can't to antything until it's fixed in new `chai-as-promised`?

Correct, if there's no stack, we can't map and highlight the error line. And `rejectedWith` even in 5.3 [passes an error message](https://github.com/domenic/chai-as-promised/blob/eecee7801efaea4c048923fd5fb9a2abe98356cf/lib/chai-as-promised.js#L215) as the `actual` object. So the error with some reportable stack is lost on its way and there's nothing to extract the stack from.

**Comment by MichalLytek** [comment]
So we have to push them in issues to make changes in new version of `chai-as-promised`? Or maybe it's a few lines of code and we can do a fork with this changes?

**Comment by ArtemGovorov** [comment]
It may not be that easy. 

Consider this: when you are doing the assertion

``` javascript
return expect(promiseThrowingError()).to.be.rejectedWith(Error, "Not Error from promise");
```

you're basically passing an expected message to compare with (`"Not Error from promise"`), so 
`chai-as-promised` has to pass the expected and the actual object [to `chai`](https://github.com/chaijs/chai/blob/cc79e11b511ecbb54e78b1b2308157ee75ee386e/lib/chai/assertion.js#L101) and because your expected object is a string, as the `actual` object it also passes not the full error with a stack, but just its message as the `actual` object. It makes sense, doesn't it?

So the `rejectedWith` function with a string argument for the expected object is doomed to lose the original exception, because following the chai API semantics it has to pass expected and actual as strings to the `chai` assertion API. I'm guessing that the `rejected` function breaking change was an attempt to address a similar issue. 

I thinks `chai` API should support passing the original error so that a plugin like `chai-as-promised` could pass it, see [my comment here](https://github.com/domenic/chai-as-promised/issues/166#issuecomment-252882205).

Having said that, there's a way to make `chai-as-promised` to work like you're expecting in your fork. You may take the latest `chai-as-promised` and apply these small changes: https://github.com/domenic/chai-as-promised/compare/master...ArtemGovorov:patch-1.

**Comment by MichalLytek** [comment]
I can do this kind of trick (but it doesn't looks like good BDD for me):

``` typescript
it("should test promise throwing error", async () => {
    const promiseThrowingError = () => {
        return new Promise((resolve, reject) => {
            return reject(new Error("Error from promise"));
        });
    };
    let error = await expect(promiseThrowingError()).to.be.rejected;
    expect(error).to.be.an.instanceof(Error);
    expect(error.message).to.equals("Error from promise");
});
```

But then it's again a problem when I expect to be rejected but it's resolved - no stack traces:

``` typescript
it("should test promise throwing error", () => {
    const promiseThrowingError = () => {
        return new Promise((resolve, reject) => {
            return resolve("Promise resolved");
        });
    };
    return expect(promiseThrowingError()).to.be.rejected;
});
```

**Comment by ArtemGovorov** [comment]
In this case:

``` javascript
it("should test promise throwing error", () => {
    const promiseThrowingError = () => {
        return new Promise((resolve, reject) => {
            return resolve("Promise resolved");
        });
    };
    return expect(promiseThrowingError()).to.be.rejected;
});
```

there's no promise error, so there's no stack. The only error here is an assertion error raised from the promise returned by the test. The stack in this case is lost because of the native Promise limitation. If you replace the native Promise object with `bluebird` with `longStackTraces`, you'll get the last line of the test reported as an error line:

``` javascript
module.exports = function (w) {

    return {
        ...
        setup: function() {
          var Promise = global.Promise = require("bluebird");
          Promise.config({
            longStackTraces: true
          });
        }
    };
};
```

<img width="976" alt="screen shot 2016-10-11 at 9 53 15 pm" src="https://cloud.githubusercontent.com/assets/979966/19269296/2a96d094-8ffd-11e6-92e2-be660b882ba4.png">

**Comment by MichalLytek** [comment]
With bluebird now everything works! 😄 
Even this example:

``` typescript
it("should test promise throwing error", () => {
    const promiseThrowingError = () => {
        return new Promise((resolve, reject) => {
            return reject(new Error("Error from promise"));
        });
    };
    return expect(promiseThrowingError())
        .to.be.rejectedWith(Error, "Not Error from promise");
});
```

So thanks! But I will let you now when I found an other use case that doesn't work ;)

**Comment by ArtemGovorov** [comment]
Bluebird should only solve the issue for the last line of your test, but I don't think it addresses the issue for the full stack, so with `chai-as-promised@6` + Bluebird, this line will not be highlighted as a part of the stack:

``` javascript
return reject(new Error("Error from promise"));
```

but with the `chai-as-promised@5.3` (or my patch I have mentioned above) it will be highlighted.
